//(c)Rey35
using System.Collections;

namespace tasks
{
	public class GlobalData
	{
		public static int version = 126;
		public static int NewID = 0;

		public const short MAX_TASK_NAME_LEN = 30;
		public const short MAX_TIMETABLE_SIZE = 24;
		public const short MAX_TASKREGION = 16;
		public const short TASK_AWARD_MAX_CHANGE_VALUE = 255;
		public const short TASK_AWARD_MAX_DISPLAY_EXP_CNT = 32;
		public const short TASK_AWARD_MAX_DISPLAY_CHAR_LEN = 64;
		public const short MAX_CONTRIB_MONSTERS = 100;
		public const short MAX_ITEM_WANTED = 10;
		public const short MAX_PREM_TASK_COUNT = 20;
		public const short MAX_OCCUPATIONS = 14;
		public const short MAX_MUTEX_TASK_COUNT = 5;
		public const short MAX_LIVING_SKILLS = 4;
		public const short MAX_TEAM_MEM_WANTED = MAX_OCCUPATIONS;
		public const short MAX_TITLE_NUM = 10;
		public const short MAX_NEEDED_TASK_COUNT = 5;
		public const short MAX_MONSTER_WANTED = 6;
		public const short MAX_PLAYER_WANTED = MAX_MONSTER_WANTED;
		public const short MAX_DIALOG_LEN = 20;
		public const short MAX_AWARD_SCALES = 6;
		public const short MAX_AWARD_CARRIER_HP_SCALES = 5;
		public const short MAX_AWARD_VAR_SCALES = 16;
		public const short MAX_COMBINED_SWITCHES = 20;

		public const short MAX_AWARD_CANDIDATES = 14;
		public const short MAX_ITEM_AWARD = 64;
		public const short MAX_MONSTER_SUMMONED = 32;
		public const short MAX_AWARD_PQ_RANKING = 32;
		public const short TASK_AWARD_MAX_DISPLAY_VALUE = 64;

		#region Supported Versions
		public static ArrayList Versions = new ArrayList(new int[]
		{
			43,
			52,
			53,
			54,
			55,
			56,
			57,
			59,
			60,
			63,
			64,
			68,
			69,
			75,
			78,
			79,
			80,
			81,
			82,
			83,
			84,
			85,
			86,
			87,
			88,
			89,
			90,
			91,
			92,
			93,
			94,
			95,
			96,
			97,
			98,
			99,
			100,
			101,
			102,
			103,
			104,
			105,
			106,
			107,
			108,
			109,
			110,
			111,
			112,
			113,
			114,
			115,
			116,
			117,
			118,
			119,
			120,
			121,
			122,
			123,
			124,
			125,
			126,
			127,
			128,
			129,
			130,
			135,
			137,
			139,
			140,
			146,
			147,
			153,
			156,
			157,
			158,
			161,
			162,
			163,
			164,
			167,
			175,
			176,
			177,
			178,
			180,
			181,
			9999
		});
		#endregion

		#region Task Enums
		public enum ENUM_TASK_TYPE
		{
			enumTTCommonOld = 0,
			enumTTRepeatedOld = 1,
			enumTTKeyOld = 2,
			enumTTBossOld = 3,
			enumTTInstanceOld = 4,
			enumTTScrollOld = 5,
			enumTTBusinessOld = 6,
			enumTTFeelingOld = 7,
			enumTTTacticsOld = 8,
			enumTTRegionOld = 9,
			enumTTSevenKillListOld = 10,
			enumTTFactionOld = 11,
			enumTTHintOld = 12,
			enumTTDaily = 100,
			enumTTLevel2 = 101,
			enumTTMajor = 102,
			enumTTBranch = 103,
			enumTTEvent = 104,
			enumTTQiShaList = 105,
			enumTTFaction = 106,
			enumTTFunction = 107,
			enumTTLegend = 108,
			enumTTQuestion = 109,
			enumTTHome = 110,
			// Not confirmed
			enumTTGrowth = 111,
			enumTTStory = 112,
			enumTTInstance = 113
		}

		public enum TaskAvailFrequency
		{
			enumTAFNormal = 0,
			enumTAFEachDay,
			enumTAFEachWeek,
			enumTAFEachMonth,
			enumTAFEachYear
		}

		public enum task_tm_type : byte
		{
			enumTaskTimeDate = 0,
			enumTaskTimeMonth,
			enumTaskTimeWeek,
			enumTaskTimeDay
		}

		public enum TaskExp
		{
			enumTaskExpVar,
			enumTaskExpConst,
			enumTaskExpOprt
		}

		public enum DynTaskTyp : byte
		{
			enumDTTNone = 0,
			enumDTTSpecialAward,
			enumDTTNormal,
			enumDTTGiftCard
		}

		public enum TaskMethod
		{
			enumTMNone = 0,
			enumTMKillNumMonster,
			enumTMCollectNumArticle,
			enumTMTalkToNPC,
			enumTMReachSite,
			enumTMWaitTime,
			enumTMAnswerQuestion,
			enumTMTinyGame,
			enumTMProtectNPC,
			enumTMNPCReachSite,
			enumTMGlobalValOK,
			enumTMLeaveSite,
			enumTMReachTreasureZone,
			enumTMKillPlayer,
			enumTMTransform,
			enumTMReachLevel,
			enumTMSimpleClientTask,
			enumTMSimpleClientTaskForceNavi,
			// Not confirmed
			enumTMIconStateID,
			enumTMReachHomeLevel,
			enumTMReachHomeFlourish,
			enumTMCollectNumHomeArticle,
			enumTMBindCarrierId,
			enumTMReachArenaTime,
			enumTMReachArenaWin,
			enumTMTaskEvent,
			enumTMReachFactionPersonScore,
			enumTMUseItems,
			enumTMHaveFactionMembersInTeam,
			enumTMReachGrowthTarget,
			enumTMOpenDialog,
			enumTMSuccTriggerEvent,
			enumTMVerifyStateLayer,
			enumTMKeyWord,
			enumTMPersonValOK
		}

		public enum TaskFinishType
		{
			enumTFTDirect = 0,
			enumTFTNPC,
			enumTFTConfirm,
			// Not confirmed
			enumTFTHomeUI
		}

		public enum ENUM_HOME_LEVEL_TYPE
		{
			enumHomeLevel = 0,
			enumHomeFactory = 1,
			enumHomeBuy = 2,
			enumHomeStone = 3,
			enumHomeWood = 4,
			enumHomeIron = 5,
			enumHomeCloth = 6,
			enumHomeFarm = 7,
			enumHomeAnimal = 8
		}

		public enum TaskAwardType
		{
			enumTATNormal = 0,
			enumTATEach,
			enumTATRatio,
			enumTATItemCount,
			// Not confirmed
			enumTATTaskEventTimeRatio,
			enumTATCarrierHp,
			enumTATVar
		}

		public enum TaskParameters
		{
			ShowByTransformed = 0,
			ShowByLev,
			PremCheckReincarnation,
			ShowByReincarnation,
			PremCheckRealmLevel,
			PremCheckRealmExpFull,
			ShowByRealmLevel,
			ShowByItems,
			PremItemsAnyOne,
			NotOpenWithItem,
			ShowByDeposit,
			ShowByRepu,
			ShowByPreTask,
			ShowByPeriod,
			ShowByFaction,
			ShowByGender,
			ShowByOccup,
			Premise_Spouse,
			ShowBySpouse,
			PremiseWeddingOwner,
			ShowByWeddingOwner,
			GM,
			ShieldUser,
			ShowByRMB,
			CharTime,
			ShowByCharTime,
			Teamwork,
			RcvByTeam,
			SharedTask,
			SharedAchieved,
			CheckTeammate,
			AllFail,
			CapFail,
			CapSucc,
			DismAsSelfFail,
			RcvChckMem,
			CntByMemPos,
			AllSucc,
			CoupleOnly,
			DistinguishedOcc,
			ShowByTeam,
			PremNeedComp,
			PremNeedCompPerson,
			PremCheckForce,
			ShowByForce,
			ShowByForceReputation,
			ShowByForceContribution,
			ShowByForceExp,
			ShowByForceSP,
			ShowByForceActivityLevel,
			PremIsKing,
			ShowByKing,
			PremNotInTeam,
			ShowByNotInTeam,
			ShowByTitle,
			ShowByHistoryStage,
			ShowByGeneralCard,
			ShowByGeneralCardRank,
			ShowByIconStateID,
			ShowByVIPLevel,
			PremNoHome,
			ShowByHomeLevel,
			ShowByHomeResourceLevel,
			ShowByHomeFactoryLevel,
			ShowByHomeFlourish,
			PremHomeStorageTask,
			ShowByHomeStorageTask,
			MonsterTotalCount,
			FinNeedComp,
			FinNeedCompPerson,
			IsLibraryTask,
			IsUniqueStorageTask,
			HasSign,
			OfflineFail,
			ItemNotTakeOff,
			AbsTime,
			MultiNpcTalk,
			ChooseOne,
			RandOne,
			ExeChildInOrder,
			ParentAlsoFail,
			ParentAlsoSucc,
			CanGiveUp,
			CanRedo,
			CanRedoAfterFailure,
			ClearAsGiveUp,
			NeedRecord,
			FailAsPlayerDie,
			DelvInZone,
			EnterRegionFail,
			LeaveRegionFail,
			LeaveForceFail,
			TransTo,
			TrigCtrl,
			AutoDeliver,
			DisplayInExclusiveUI,
			ReadyToNotifyServer,
			UsedInTokenShop,
			DeathTrig,
			ClearAcquired,
			ShowPrompt,
			KeyTask,
			SkillTask,
			CanSeekOut,
			ShowDirection,
			Marriage,
			SwitchSceneFail,
			Hidden,
			DeliverySkill,
			ShowGfxFinished,
			ChangePQRanking,
			CompareItemAndInventory,
			TowerTask,
			HomeTask,
			DeliverInHostHome,
			FinishInHostHome,
			PQTask,
			PQSubTask,
			ClearContrib,
			ShowByNeedRecordTasksNum,
			ShowByFactionContrib,
			AccountTaskLimit,
			RoleTaskLimit,
			LeaveFactionFail,
			NotIncCntWhenFailed,
			NotClearItemWhenFailed,
			DisplayInTitleTaskUI,
			CanAwardOnCarrier,
			PreReachArenaWinCount,
			ShowByReachArenaWinCount,
			WriteSpecialLog,
			ShowByPreFactionScore,
			ShowByPreFactionMoney,
			ShowByPreFactionPersonScore,
			CheckFactionMem,
			ByFactionScore,
			SpecailLogicTask,
			BecomeMentor,
			ShowMentorMorality,
			ShowMentorStudent,
			DiscardedTask,
			NoCheckTitleGot,
			ShowCoupleIntimacy,
			ShowByDeposit2,
			RESERVED145,
			RecordFinishCount,
			ShowCamp,
			ShowCampPower,
			ReturnCampPower,
			TeamHaveRecaller,
			BindedRecaller,
			ShowNeedFriendPoint,
			HistoryVarTask,
			PremRank,
			DeliverByUI,
			WarTaskAward,
			HideOtherPlayer,
			RESERVED158,
			RESERVED159,
			RESERVED160
		}

		public enum SERVICE_TYPE : uint
		{
			NPC_TALK = 0x80000000,
			NPC_SELL = 0x80000001,
			NPC_BUY = 0x80000002,
			NPC_REPAIR = 0x80000003,
			NPC_INSTALL = 0x80000004,
			NPC_UNINSTALL = 0x80000005,
			NPC_GIVE_TASK = 0x80000006,
			NPC_COMPLETE_TASK = 0x80000007,
			NPC_GIVE_TASK_MATTER = 0x80000008,
			NPC_SKILL = 0x80000009,
			NPC_HEAL = 0x8000000A,
			NPC_TRANSMIT = 0x8000000B,
			NPC_TRANSPORT = 0x8000000C,
			NPC_PROXY = 0x8000000D,
			NPC_STORAGE = 0x8000000E,
			NPC_MAKE = 0x8000000F,
			NPC_DECOMPOSE = 0x80000010,
			TALK_RETURN = 0x80000011,
			TALK_EXIT = 0x80000012,
			NPC_STORAGE_PASSWORD = 0x80000013,
			NPC_IDENTIFY = 0x80000014,
			TALK_GIVEUP_TASK = 0x80000015,
			NPC_WAR_TOWERBUILD = 0x80000016,
			NPC_RESETPROP = 0x80000017,
			NPC_PETNAME = 0x80000018,
			NPC_PETLEARNSKILL = 0x80000019,
			NPC_PETFORGETSKILL = 0x8000001A,
			NPC_EQUIPBIND = 0x8000001B,
			NPC_EQUIPDESTROY = 0x8000001C,
			NPC_EQUIPUNDESTROY = 0x8000001D,
			NPC_ACCOUNT_STORAGE = 0x8000001E,
			NPC_ENGRAVE = 0x8000001F,
			NPC_RANDPROP = 0x80000020
		}
		#endregion

		#region Task Elements Types
		public enum TASKELEMENTS_TYPE
		{
			NONE,
			TASKS_DELV_WORLD,
			TASKS_ENTER_REGION_WORLD,
			TASKS_LEAVE_REGION_WORLD,
			TASKS_TRANS_WLD_ID,
			TASKS_MONS_CTRL,
			TASKS_DELV_NPC,
			TASKS_AWARD_NPC,
			TASKS_CHANGE_KEY,
			TASKS_MONSTERS_CONTRIB,
			TASKS_PREM_ITEMS,
			TASKS_GIVEN_ITEMS,
			TASKS_PREM_1_KEY_VALUE_LEFT_NUM,
			TASKS_PREM_1_KEY_VALUE_RIGHT_NUM,
			TASKS_PREM_2_KEY_VALUE_LEFT_NUM,
			TASKS_PREM_2_KEY_VALUE_RIGHT_NUM,
			TASKS_PREM_TITLES,
			TASKS_MATTERS_PLAYER_WANTED,
			TASKS_MONSTER_WANTED_MONSTERS,
			TASKS_MONSTER_WANTED_ITEMS,
			TASKS_ITEMS_WANTED,
			TASKS_REACH_SITE_ID,
			TASKS_TREASURE_ZONE_MAP_ID,
			TASKS_LEAVE_SITE_ID,
			TASKS_FIN_1_KEY_VALUE_LEFT_NUM,
			TASKS_FIN_1_KEY_VALUE_RIGHT_NUM,
			TASKS_FIN_2_KEY_VALUE_LEFT_NUM,
			TASKS_FIN_2_KEY_VALUE_RIGHT_NUM,
			TASKS_HOME_ITEMS_WANTED,
			TASKS_TM_BIND_CARRTER_ID,
			TASKS_TASK_EVENT_MONSTER_DATA,
			TASKS_TASK_EVENT_MINE_DATA,
			TASKS_TASK_EVENT_TASK_DATA,
			TASKS_AWARD_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_SUCCESS_MONS_CTRL,
			TASKS_AWARD_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_RATIO_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_BY_RATIO_SUCCESS_MONS_CTRL,
			TASKS_AWARD_BY_RATIO_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_BY_RATIO_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_RATIO_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_BY_RATIO_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_BY_RATIO_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_RATIO_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_ITEMS_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_BY_ITEMS_SUCCESS_MONS_CTRL,
			TASKS_AWARD_BY_ITEMS_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_BY_ITEMS_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_ITEMS_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_BY_ITEMS_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_BY_ITEMS_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_ITEMS_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_MONS_CTRL,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_MONS_CTRL,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_FAIL_MONS_CTRL,
			TASKS_AWARD_FAIL_CAND_ITEMS,
			TASKS_AWARD_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_FAIL_CHANGE_KEY,
			TASKS_AWARD_FAIL_TITLE_AWARD,
			TASKS_AWARD_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_FAIL_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_RATIO_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_BY_RATIO_FAIL_MONS_CTRL,
			TASKS_AWARD_BY_RATIO_FAIL_CAND_ITEMS,
			TASKS_AWARD_BY_RATIO_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_RATIO_FAIL_CHANGE_KEY,
			TASKS_AWARD_BY_RATIO_FAIL_TITLE_AWARD,
			TASKS_AWARD_BY_RATIO_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_RATIO_FAIL_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_ITEMS_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_BY_ITEMS_FAIL_MONS_CTRL,
			TASKS_AWARD_BY_ITEMS_FAIL_CAND_ITEMS,
			TASKS_AWARD_BY_ITEMS_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_ITEMS_FAIL_CHANGE_KEY,
			TASKS_AWARD_BY_ITEMS_FAIL_TITLE_AWARD,
			TASKS_AWARD_BY_ITEMS_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_ITEMS_FAIL_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_MONS_CTRL,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_CAND_ITEMS,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_CHANGE_KEY,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_TITLE_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_MONS_CTRL,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_CAND_ITEMS,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_CHANGE_KEY,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_TITLE_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_FACTION_TARGET_DATA,
			TASKS_SL_USE_ITEM_IDS,
			TASKS_SL_COMPLETE_TASK_IDS,
			TASKS_DELV_REGION,
			TASKS_ENTER_REGION,
			TASKS_LEAVE_REGION,
			TASKS_REACH_SITE,
			TASKS_LEAVE_SITE,
			TASKS_GLOBAL_KEY_FOR_AWARD_VAR,
			TASKS_AWARD_BY_VAR_SUCCESS_TRANS_WLD_ID,
			TASKS_AWARD_BY_VAR_SUCCESS_MONS_CTRL,
			TASKS_AWARD_BY_VAR_SUCCESS_CAND_ITEMS,
			TASKS_AWARD_BY_VAR_SUCCESS_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_VAR_SUCCESS_CHANGE_KEY,
			TASKS_AWARD_BY_VAR_SUCCESS_TITLE_AWARD,
			TASKS_AWARD_BY_VAR_SUCCESS_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_VAR_SUCCESS_FACTION_TARGET_DATA,
			TASKS_AWARD_BY_VAR_FAIL_TRANS_WLD_ID,
			TASKS_AWARD_BY_VAR_FAIL_MONS_CTRL,
			TASKS_AWARD_BY_VAR_FAIL_CAND_ITEMS,
			TASKS_AWARD_BY_VAR_FAIL_PQ_RANKING_AWARD,
			TASKS_AWARD_BY_VAR_FAIL_CHANGE_KEY,
			TASKS_AWARD_BY_VAR_FAIL_TITLE_AWARD,
			TASKS_AWARD_BY_VAR_FAIL_SUMMONED_MONSTERS,
			TASKS_AWARD_BY_VAR_FAIL_FACTION_TARGET_DATA,
			TASKS_AWARD_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_BY_RATIO_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_BY_ITEMS_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_BY_VAR_SUCCESS_INVITER_AWARD,
			TASKS_AWARD_FAIL_INVITER_AWARD,
			TASKS_AWARD_BY_RATIO_FAIL_INVITER_AWARD,
			TASKS_AWARD_BY_ITEMS_FAIL_INVITER_AWARD,
			TASKS_AWARD_BY_TASK_EVENT_RATIO_FAIL_INVITER_AWARD,
			TASKS_AWARD_BY_CARRIER_HP_RATIO_FAIL_INVITER_AWARD,
			TASKS_AWARD_BY_VAR_FAIL_INVITER_AWARD,
			TASKS_FAIL_1_KEY_VALUE_LEFT_NUM,
			TASKS_FAIL_1_KEY_VALUE_RIGHT_NUM,
			TASKS_FAIL_2_KEY_VALUE_LEFT_NUM,
			TASKS_FAIL_2_KEY_VALUE_RIGHT_NUM,
			TASKS_PROP_SUMMONED_MONSTERS
		};
		#endregion
	}
}
//(c)Rey35