/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libtask'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct talk_proc::window;
struct talk_proc::option;
struct TASK_EXPRESSION;
struct PLAYER_WANTED;
struct MONSTER_WANTED;
struct ITEM_WANTED;
struct HOME_ITEM_WANTED;
struct TITLE_AWARD;
struct MONSTERS_SUMMONED;
struct MONSTERS_CONTRIB;
struct RANKING_AWARD;
struct TEAM_MEM_WANTED;
struct AWARD_ITEMS_CAND;
struct AWARD_MONSTERS_SUMMONED;
struct AWARD_PQ_RANKING;
struct AWARD_DATA;
struct AWARD_RATIO_SCALE;
struct AWARD_ITEMS_SCALE;
struct Task_Region;

/* 755 */
typedef unsigned __int16 task_char;

/* 813 */
struct task_tm
{
  int year;
  int month;
  int day;
  int hour;
  int min;
  int wday;
};

/* 795 */
union ZONE_VERT::$E1B1822422B944930F1081DC91814C5B
{
  float v[3];
};

/* 794 */
struct ZONE_VERT
{
  ZONE_VERT::$E1B1822422B944930F1081DC91814C5B _anon_0;
};

/* 827 */
struct COMPARE_KEY_VALUE
{
  int nLeftType;
  int lLeftNum;
  int nCompOper;
  int nRightType;
  int lRightNum;
};

/* 792 */
enum ENUM_HOME_LEVEL_TYPE : __int32
{
  enumHomeLevel = 0x0,
  enumHomeFactory = 0x1,
  enumHomeBuy = 0x2,
  enumHomeStone = 0x3,
  enumHomeWood = 0x4,
  enumHomeIron = 0x5,
  enumHomeCloth = 0x6,
  enumHomeFarm = 0x7,
  enumHomeAnimal = 0x8,
};

/* 829 */
struct ATaskTemplFixedData
{
  unsigned int m_ID;
  task_char m_szName[30];
  bool m_bHasSign;
  __attribute__((packed)) __attribute__((aligned(1))) task_char *m_pszSignature;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulType;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTimeLimit;
  bool m_bOfflineFail;
  bool m_bAbsFail;
  __attribute__((packed)) __attribute__((aligned(1))) task_tm m_tmAbsFailTime;
  bool m_bItemNotTakeOff;
  bool m_bAbsTime;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTimetable;
  char m_tmType[24];
  __attribute__((packed)) __attribute__((aligned(1))) task_tm *m_tmStart;
  __attribute__((packed)) __attribute__((aligned(1))) task_tm *m_tmEnd;
  __attribute__((packed)) __attribute__((aligned(1))) int m_lAvailFrequency;
  __attribute__((packed)) __attribute__((aligned(1))) int m_lPeriodLimit;
  bool m_bChooseOne;
  bool m_bRandOne;
  bool m_bExeChildInOrder;
  bool m_bParentAlsoFail;
  bool m_bParentAlsoSucc;
  bool m_bCanGiveUp;
  bool m_bCanRedo;
  bool m_bCanRedoAfterFailure;
  bool m_bClearAsGiveUp;
  bool m_bNeedRecord;
  bool m_bFailAsPlayerDie;
  unsigned int m_ulMaxReceiver;
  bool m_bDelvInZone;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulDelvWorld;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulDelvRegionCnt;
  __attribute__((packed)) __attribute__((aligned(1))) Task_Region *m_pDelvRegion;
  bool m_bEnterRegionFail;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulEnterRegionWorld;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulEnterRegionCnt;
  __attribute__((packed)) __attribute__((aligned(1))) Task_Region *m_pEnterRegion;
  bool m_bLeaveRegionFail;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulLeaveRegionWorld;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulLeaveRegionCnt;
  __attribute__((packed)) __attribute__((aligned(1))) Task_Region *m_pLeaveRegion;
  bool m_bLeaveForceFail;
  bool m_bTransTo;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTransWldId;
  __attribute__((packed)) __attribute__((aligned(1))) ZONE_VERT m_TransPt;
  __attribute__((packed)) __attribute__((aligned(1))) int m_lMonsCtrl;
  bool m_bTrigCtrl;
  bool m_bAutoDeliver;
  bool m_bDisplayInExclusiveUI;
  bool m_bReadyToNotifyServer;
  bool m_bUsedInTokenShop;
  bool m_bDeathTrig;
  bool m_bClearAcquired;
  unsigned int m_ulSuitableLevel;
  bool m_bShowPrompt;
  bool m_bKeyTask;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulDelvNPC;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulAwardNPC;
  bool m_bSkillTask;
  bool m_bCanSeekOut;
  bool m_bShowDirection;
  bool m_bMarriage;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulChangeKeyCnt;
  __attribute__((packed)) __attribute__((aligned(1))) int *m_plChangeKey;
  __attribute__((packed)) __attribute__((aligned(1))) int *m_plChangeKeyValue;
  __attribute__((packed)) __attribute__((aligned(1))) bool *m_pbChangeType;
  bool m_bSwitchSceneFail;
  bool m_bHidden;
  bool m_bDeliverySkill;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iDeliveredSkillID;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iDeliveredSkillLevel;
  bool m_bShowGfxFinished;
  bool m_bChangePQRanking;
  bool m_bCompareItemAndInventory;
  unsigned int m_ulInventorySlotNum;
  bool m_bTowerTask;
  bool m_bHomeTask;
  bool m_bDeliverInHostHome;
  bool m_bFinishInHostHome;
  bool m_bPQTask;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPQExpCnt;
  __attribute__((packed)) __attribute__((aligned(1))) char (*m_pszPQExp)[64];
  __attribute__((packed)) __attribute__((aligned(1))) TASK_EXPRESSION (*m_pPQExpArr)[64];
  bool m_bPQSubTask;
  bool m_bClearContrib;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulMonsterContribCnt;
  __attribute__((packed)) __attribute__((aligned(1))) MONSTERS_CONTRIB *m_MonstersContrib;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremNeedRecordTasksNum;
  bool m_bShowByNeedRecordTasksNum;
  int m_iPremiseFactionContrib;
  bool m_bShowByFactionContrib;
  bool m_bAccountTaskLimit;
  bool m_bRoleTaskLimit;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulAccountTaskLimitCnt;
  bool m_bLeaveFactionFail;
  bool m_bNotIncCntWhenFailed;
  bool m_bNotClearItemWhenFailed;
  bool m_bDisplayInTitleTaskUI;
  unsigned __int8 m_ucPremiseTransformedForm;
  bool m_bShowByTransformed;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Lev_Min;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Lev_Max;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_bPremCheckMaxHistoryLevel;
  bool m_bShowByLev;
  bool m_bPremCheckReincarnation;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremReincarnationMin;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremReincarnationMax;
  bool m_bShowByReincarnation;
  bool m_bPremCheckRealmLevel;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremRealmLevelMin;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremRealmLevelMax;
  bool m_bPremCheckRealmExpFull;
  bool m_bShowByRealmLevel;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremItems;
  __attribute__((packed)) __attribute__((aligned(1))) ITEM_WANTED *m_PremItems;
  bool m_bShowByItems;
  bool m_bPremItemsAnyOne;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulGivenItems;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulGivenCmnCount;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulGivenTskCount;
  __attribute__((packed)) __attribute__((aligned(1))) ITEM_WANTED *m_GivenItems;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Deposit;
  bool m_bShowByDeposit;
  __attribute__((packed)) __attribute__((aligned(1))) int m_lPremise_Reputation;
  __attribute__((packed)) __attribute__((aligned(1))) int m_lPremise_RepuMax;
  bool m_bShowByRepu;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Task_Count;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Tasks[20];
  bool m_bShowByPreTask;
  unsigned int m_ulPremise_Task_Least_Num;
  unsigned int m_ulPremise_Period;
  bool m_bShowByPeriod;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Faction;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremise_FactionRole;
  bool m_bShowByFaction;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulGender;
  bool m_bShowByGender;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulOccupations;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_Occupations[12];
  bool m_bShowByOccup;
  bool m_bPremise_Spouse;
  bool m_bShowBySpouse;
  bool m_bPremiseWeddingOwner;
  bool m_bShowByWeddingOwner;
  bool m_bGM;
  bool m_bShieldUser;
  bool m_bShowByRMB;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremRMBMin;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremRMBMax;
  bool m_bCharTime;
  bool m_bShowByCharTime;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iCharStartTime;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iCharEndTime;
  __attribute__((packed)) __attribute__((aligned(1))) task_tm m_tmCharEndTime;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulCharTimeGreaterThan;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremise_Cotask;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulCoTaskCond;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulMutexTaskCount;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulMutexTasks[5];
  __attribute__((packed)) __attribute__((aligned(1))) int m_lSkillLev[4];
  char m_DynTaskType;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulSpecialAward;
  bool m_bTeamwork;
  bool m_bRcvByTeam;
  bool m_bSharedTask;
  bool m_bSharedAchieved;
  bool m_bCheckTeammate;
  __attribute__((packed)) __attribute__((aligned(1))) float m_fTeammateDist;
  bool m_bAllFail;
  bool m_bCapFail;
  bool m_bCapSucc;
  __attribute__((packed)) __attribute__((aligned(1))) float m_fSuccDist;
  bool m_bDismAsSelfFail;
  bool m_bRcvChckMem;
  float m_fRcvMemDist;
  bool m_bCntByMemPos;
  __attribute__((packed)) __attribute__((aligned(1))) float m_fCntMemDist;
  bool m_bAllSucc;
  bool m_bCoupleOnly;
  bool m_bDistinguishedOcc;
  unsigned int m_ulTeamMemsWanted;
  TEAM_MEM_WANTED *m_TeamMemsWanted;
  bool m_bShowByTeam;
  bool m_bPremNeedComp;
  __attribute__((packed)) __attribute__((aligned(1))) int m_nPremExp1AndOrExp2;
  __attribute__((packed)) __attribute__((aligned(1))) COMPARE_KEY_VALUE m_Prem1KeyValue;
  __attribute__((packed)) __attribute__((aligned(1))) COMPARE_KEY_VALUE m_Prem2KeyValue;
  bool m_bPremCheckForce;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremForce;
  bool m_bShowByForce;
  int m_iPremForceReputation;
  bool m_bShowByForceReputation;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremForceContribution;
  bool m_bShowByForceContribution;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremForceExp;
  bool m_bShowByForceExp;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremForceSP;
  bool m_bShowByForceSP;
  int m_iPremForceActivityLevel;
  bool m_bShowByForceActivityLevel;
  bool m_bPremIsKing;
  bool m_bShowByKing;
  bool m_bPremNotInTeam;
  bool m_bShowByNotInTeam;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_iPremTitleNumTotal;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_iPremTitleNumRequired;
  __attribute__((packed)) __attribute__((aligned(1))) int *m_PremTitles;
  bool m_bShowByTitle;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHistoryStageIndex[2];
  bool m_bShowByHistoryStage;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremGeneralCardCount;
  bool m_bShowByGeneralCard;
  int m_iPremGeneralCardRank;
  unsigned int m_ulPremGeneralCardRankCount;
  bool m_bShowByGeneralCardRank;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPremIconStateID;
  bool m_bShowByIconStateID;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iVIPLevelMin;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iVIPLevelMax;
  bool m_bShowByVIPLevel;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeLevelMin;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeLevelMax;
  bool m_bShowByHomeLevel;
  int m_iPremHomeResourceLevelType;
  int m_iPremHomeResourceLevelMin;
  int m_iPremHomeResourceLevelMax;
  bool m_bShowByHomeResourceLevel;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeFactoryLevelType;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeFactoryLevelMin;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeFactoryLevelMax;
  bool m_bShowByHomeFactoryLevel;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeFlourishMin;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iPremHomeFlourishMax;
  bool m_bShowByHomeFlourish;
  bool m_bPremHomeStorageTask;
  bool m_bShowByHomeStorageTask;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_enumMethod;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_enumFinishType;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPlayerWanted;
  __attribute__((packed)) __attribute__((aligned(1))) PLAYER_WANTED *m_PlayerWanted;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulMonsterWanted;
  __attribute__((packed)) __attribute__((aligned(1))) MONSTER_WANTED *m_MonsterWanted;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulItemsWanted;
  __attribute__((packed)) __attribute__((aligned(1))) ITEM_WANTED *m_ItemsWanted;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulGoldWanted;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iFactionContribWanted;
  __attribute__((packed)) __attribute__((aligned(1))) int m_iFactionExpContribWanted;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulNPCToProtect;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulProtectTimeLen;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulNPCMoving;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulNPCDestSite;
  __attribute__((packed)) __attribute__((aligned(1))) Task_Region *m_pReachSite;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulReachSiteCnt;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulReachSiteId;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulWaitTime;
  __attribute__((packed)) __attribute__((aligned(1))) ZONE_VERT m_TreasureStartZone;
  unsigned __int8 m_ucZonesNumX;
  unsigned __int8 m_ucZonesNumZ;
  unsigned __int8 m_ucZoneSide;
  Task_Region *m_pLeaveSite;
  unsigned int m_ulLeaveSiteCnt;
  unsigned int m_ulLeaveSiteId;
  bool m_bFinNeedComp;
  __attribute__((packed)) __attribute__((aligned(1))) int m_nFinExp1AndOrExp2;
  __attribute__((packed)) __attribute__((aligned(1))) COMPARE_KEY_VALUE m_Fin1KeyValue;
  __attribute__((packed)) __attribute__((aligned(1))) COMPARE_KEY_VALUE m_Fin2KeyValue;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulExpCnt;
  __attribute__((packed)) __attribute__((aligned(1))) char (*m_pszExp)[64];
  __attribute__((packed)) __attribute__((aligned(1))) TASK_EXPRESSION (*m_pExpArr)[64];
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTaskCharCnt;
  __attribute__((packed)) __attribute__((aligned(1))) task_char (*m_pTaskChar)[64];
  unsigned __int8 m_ucTransformedForm;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulReachLevel;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulReachReincarnationCount;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulReachRealmLevel;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_uiEmotion;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTMIconStateID;
  __attribute__((packed)) __attribute__((aligned(1))) ENUM_HOME_LEVEL_TYPE m_ulTMHomeLevelType;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTMReachHomeLevel;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulTMReachHomeFlourish;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulHomeItemsWanted;
  __attribute__((packed)) __attribute__((aligned(1))) HOME_ITEM_WANTED *m_HomeItemsWanted;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulAwardType_S;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulAwardType_F;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_DATA *m_Award_S;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_DATA *m_Award_F;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_RATIO_SCALE *m_AwByRatio_S;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_RATIO_SCALE *m_AwByRatio_F;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_ITEMS_SCALE *m_AwByItems_S;
  __attribute__((packed)) __attribute__((aligned(1))) AWARD_ITEMS_SCALE *m_AwByItems_F;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulParent;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulPrevSibling;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulNextSibling;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned int m_ulFirstChild;
  bool m_bIsLibraryTask;
  __attribute__((packed)) __attribute__((aligned(1))) float m_fLibraryTasksProbability;
  bool m_bIsUniqueStorageTask;
  int m_iWorldContribution;
};

/* 395 */
typedef unsigned __int16 namechar;

/* 599 */
struct talk_proc
{
  namechar text[64];
  unsigned int id_talk;
  int num_window;
  talk_proc::window *windows;
};

/* 763 */
struct __cppobj ATaskTempl : ATaskTemplFixedData
{
  int (**_vptr.ATaskTempl)(...);
  task_char *m_pwstrDescript;
  task_char *m_pwstrOkText;
  task_char *m_pwstrNoText;
  task_char *m_pwstrTribute;
  char m_szFilePath[260];
  ATaskTempl *m_pParent;
  ATaskTempl *m_pPrevSibling;
  ATaskTempl *m_pNextSibling;
  ATaskTempl *m_pFirstChild;
  unsigned __int8 m_uDepth;
  unsigned int m_ulMask;
  int m_nSubCount;
  unsigned __int8 m_uValidCount;
  unsigned int m_ulPremStorageItem;
  talk_proc m_DelvTaskTalk;
  talk_proc m_UnqualifiedTalk;
  talk_proc m_DelvItemTalk;
  talk_proc m_ExeTalk;
  talk_proc m_AwardTalk;
};

/* 828 */
struct Task_Region
{
  ZONE_VERT zvMin;
  ZONE_VERT zvMax;
};

/* 785 */
struct TASK_EXPRESSION
{
  int type;
  float value;
};

/* 803 */
struct MONSTERS_CONTRIB
{
  unsigned int m_ulMonsterTemplId;
  int m_iWholeContrib;
  int m_iShareContrib;
  int m_iPersonalWholeContrib;
};

/* 798 */
struct __attribute__((packed)) __attribute__((aligned(1))) ITEM_WANTED
{
  unsigned int m_ulItemTemplId;
  bool m_bCommonItem;
  unsigned int m_ulItemNum;
  float m_fProb;
  int m_lPeriod;
};

/* 805 */
struct TEAM_MEM_WANTED
{
  unsigned int m_ulLevelMin;
  unsigned int m_ulLevelMax;
  unsigned int m_ulRace;
  unsigned int m_ulOccupation;
  unsigned int m_ulGender;
  unsigned int m_ulMinCount;
  unsigned int m_ulMaxCount;
  unsigned int m_ulTask;
  int m_iForce;
};

/* 758 */
struct Kill_Player_Requirements
{
  unsigned int m_ulOccupations;
  int m_iMinLevel;
  int m_iMaxLevel;
  int m_iGender;
  int m_iForce;
};

/* 796 */
struct __attribute__((packed)) __attribute__((aligned(1))) PLAYER_WANTED
{
  unsigned int m_ulPlayerNum;
  unsigned int m_ulDropItemId;
  unsigned int m_ulDropItemCount;
  bool m_bDropCmnItem;
  float m_fDropProb;
  Kill_Player_Requirements m_Requirements;
};

/* 797 */
struct __attribute__((packed)) __attribute__((aligned(2))) MONSTER_WANTED
{
  unsigned int m_ulMonsterTemplId;
  unsigned int m_ulMonsterNum;
  unsigned int m_ulDropItemId;
  unsigned int m_ulDropItemCount;
  bool m_bDropCmnItem;
  float m_fDropProb;
  bool m_bKillerLev;
  int m_iDPH;
  int m_iDPS;
};

/* 799 */
struct HOME_ITEM_WANTED
{
  unsigned int m_ulHomeItemTid;
  unsigned int m_ulHomeItemCount;
};

/* 809 */
struct __attribute__((packed)) __attribute__((aligned(2))) AWARD_DATA
{
  unsigned int m_ulGoldNum;
  unsigned int m_ulExp;
  unsigned int m_ulRealmExp;
  bool m_bExpandRealmLevelMax;
  unsigned int m_ulNewTask;
  unsigned int m_ulSP;
  int m_lReputation;
  unsigned int m_ulNewPeriod;
  unsigned int m_ulNewRelayStation;
  unsigned int m_ulStorehouseSize;
  unsigned int m_ulStorehouseSize2;
  unsigned int m_ulStorehouseSize3;
  unsigned int m_ulStorehouseSize4;
  int m_lInventorySize;
  unsigned int m_ulPetInventorySize;
  unsigned int m_ulFuryULimit;
  unsigned int m_ulTransWldId;
  ZONE_VERT m_TransPt;
  int m_lMonsCtrl;
  bool m_bTrigCtrl;
  bool m_bUseLevCo;
  bool m_bDivorce;
  bool m_bSendMsg;
  int m_nMsgChannel;
  unsigned int m_ulCandItems;
  AWARD_ITEMS_CAND *m_CandItems;
  unsigned int m_ulSummonedMonsters;
  AWARD_MONSTERS_SUMMONED *m_SummonedMonsters;
  bool m_bAwardDeath;
  bool m_bAwardDeathWithLoss;
  unsigned int m_ulDividend;
  bool m_bAwardSkill;
  int m_iAwardSkillID;
  int m_iAwardSkillLevel;
  int m_iSoloTowerChallengeScore;
  unsigned int m_ulSpecifyContribTaskID;
  unsigned int m_ulSpecifyContribSubTaskID;
  unsigned int m_ulSpecifyContrib;
  unsigned int m_ulContrib;
  unsigned int m_ulRandContrib;
  unsigned int m_ulLowestcontrib;
  int m_iFactionContrib;
  int m_iFactionExpContrib;
  unsigned int m_ulPQRankingAwardCnt;
  AWARD_PQ_RANKING *m_PQRankingAward;
  unsigned int m_ulChangeKeyCnt;
  int *m_plChangeKey;
  int *m_plChangeKeyValue;
  bool *m_pbChangeType;
  unsigned int m_ulHistoryChangeCnt;
  int *m_plHistoryChangeKey;
  int *m_plHistoryChangeKeyValue;
  bool *m_pbHistoryChangeType;
  bool m_bMulti;
  int m_nNumType;
  int m_lNum;
  unsigned int m_ulDisplayKeyCnt;
  int *m_plDisplayKey;
  unsigned int m_ulExpCnt;
  char (*m_pszExp)[64];
  TASK_EXPRESSION (*m_pExpArr)[64];
  unsigned int m_ulTaskCharCnt;
  task_char (*m_pTaskChar)[64];
  int m_iForceContribution;
  int m_iForceReputation;
  int m_iForceActivity;
  int m_iForceSetRepu;
  int m_iTaskLimit;
  unsigned int m_ulTitleNum;
  TITLE_AWARD *m_pTitleAward;
  int m_iLeaderShip;
  int m_iWorldContribution;
  int m_iHomeResource[5];
  bool m_bCreateHome;
};

/* 810 */
struct AWARD_RATIO_SCALE
{
  unsigned int m_ulScales;
  float m_Ratios[5];
  AWARD_DATA *m_Awards;
};

/* 811 */
struct AWARD_ITEMS_SCALE
{
  unsigned int m_ulScales;
  unsigned int m_ulItemId;
  unsigned int m_Counts[5];
  AWARD_DATA *m_Awards;
};

/* 600 */
struct talk_proc::window
{
  unsigned int id;
  unsigned int id_parent;
  int talk_text_len;
  namechar *talk_text;
  int num_option;
  talk_proc::option *options;
};

/* 806 */
struct __attribute__((packed)) __attribute__((aligned(1))) AWARD_ITEMS_CAND
{
  unsigned int m_ulAwardItems;
  unsigned int m_ulAwardCmnItems;
  unsigned int m_ulAwardTskItems;
  ITEM_WANTED *m_AwardItems;
  bool m_bRandChoose;
};

/* 807 */
struct __attribute__((packed)) __attribute__((aligned(2))) AWARD_MONSTERS_SUMMONED
{
  unsigned int m_ulMonsterNum;
  bool m_bRandChoose;
  unsigned int m_ulSummonRadius;
  bool m_bDeathDisappear;
  MONSTERS_SUMMONED *m_Monsters;
};

/* 808 */
struct __attribute__((packed)) __attribute__((aligned(1))) AWARD_PQ_RANKING
{
  bool m_bAwardByProf;
  unsigned int m_ulRankingAwardNum;
  RANKING_AWARD *m_RankingAward;
};

/* 800 */
struct TITLE_AWARD
{
  unsigned int m_ulTitleID;
  int m_lPeriod;
};

/* 601 */
struct talk_proc::option
{
  unsigned int id;
  namechar text[64];
  unsigned int param;
};

/* 802 */
struct MONSTERS_SUMMONED
{
  unsigned int m_ulMonsterTemplId;
  unsigned int m_ulMonsterNum;
  float m_fSummonProb;
  int m_lPeriod;
};

/* 804 */
struct __attribute__((packed)) __attribute__((aligned(1))) RANKING_AWARD
{
  unsigned int m_iRankingStart;
  unsigned int m_iRankingEnd;
  bool m_bCommonItem;
  unsigned int m_ulAwardItemId;
  unsigned int m_ulAwardItemNum;
  int m_lPeriod;
};

