/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libtask'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 789 */
enum DynTaskType : __int32
{
  enumDTTNone = 0x0,
  enumDTTSpecialAward = 0x1,
  enumDTTNormal = 0x2,
  enumDTTGiftCard = 0x3,
};

