/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libtask'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 791 */
enum ENUM_TASK_TYPE : __int32
{
  enumTTDaily = 0x64,
  enumTTLevel2 = 0x65,
  enumTTMajor = 0x66,
  enumTTBranch = 0x67,
  enumTTEvent = 0x68,
  enumTTQiShaList = 0x69,
  enumTTFaction = 0x6A,
  enumTTFunction = 0x6B,
  enumTTLegend = 0x6C,
  enumTTQuestion = 0x6D,
  enumTTHome = 0x6E,
  enumTTEnd = 0x6F,
};

