/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libtask'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 793 */
struct TASK_PACK_HEADER
{
  unsigned int magic;
  unsigned int version;
  unsigned int item_count;
};

