/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libtask'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 812 */
enum task_tm_type : __int32
{
  enumTaskTimeDate = 0x0,
  enumTaskTimeMonth = 0x1,
  enumTaskTimeWeek = 0x2,
  enumTaskTimeDay = 0x3,
};

